/**
 * Slice 4 transform: an Angular `@Injectable` service -> a plain TypeScript
 * module.
 *
 * A service is not a component: it stays a class. So this is *in-place surgery*
 * on the AST (via ts-morph), not a rebuild. Method bodies, `this.` references,
 * types and generics are preserved verbatim; only the Angular-specific edges are
 * touched, and everything the harness cannot decide is left as visible residue:
 *
 *  - `@Injectable` decorator            -> removed
 *  - `inject(X)` field                  -> constructor parameter (manual DI), flagged
 *  - Angular lifecycle interfaces       -> dropped from `implements`
 *  - `ngOnInit` / `ngOnDestroy` / …     -> kept, but flagged (no longer auto-called)
 *  - `@angular/core` DI/lifecycle imports -> pruned
 *  - OpenAPI-*generated* API clients    -> NOT migrated; flagged to regenerate
 */

import { Project, Scope, SyntaxKind, Node } from 'ts-morph';
import prettier from 'prettier';
import type { ServiceModel, ServiceDep } from './ir/service.js';

/** `@angular/core` names that only make sense in the Angular DI/lifecycle world. */
const ANGULAR_CORE_DROP = new Set([
  'Injectable',
  'inject',
  'Inject',
  'Optional',
  'Self',
  'SkipSelf',
  'Host',
  'OnInit',
  'OnDestroy',
  'OnChanges',
  'AfterViewInit',
  'AfterContentInit',
  'AfterViewChecked',
  'AfterContentChecked',
  'DoCheck',
]);

const LIFECYCLE_INTERFACES = new Set([
  'OnInit',
  'OnDestroy',
  'OnChanges',
  'AfterViewInit',
  'AfterContentInit',
  'AfterViewChecked',
  'AfterContentChecked',
  'DoCheck',
]);

const LIFECYCLE_HOOKS = new Set([
  'ngOnInit',
  'ngOnDestroy',
  'ngOnChanges',
  'ngAfterViewInit',
  'ngAfterContentInit',
  'ngAfterViewChecked',
  'ngAfterContentChecked',
  'ngDoCheck',
]);

export interface ServiceTransformResult {
  ok: boolean;
  /** The emitted `.ts` module (only meaningful when ok). */
  ts: string;
  errors: string[];
  todos: string[];
  /** Structured summary for reporting; null when no @Injectable class was found. */
  model: ServiceModel | null;
}

/** Is this an OpenAPI-generated API client (regenerate, don't hand-migrate)? */
export function isGeneratedService(source: string, path: string): boolean {
  if (/[/\\]generated[/\\]/.test(path)) return true;
  return /auto generated by OpenAPI Generator|NOTE: This class is auto generated/i.test(source);
}

export async function transformService(
  source: string,
  path = 'service.ts',
): Promise<ServiceTransformResult> {
  const project = new Project({ useInMemoryFileSystem: true, skipAddingFilesFromTsConfig: true });
  const sf = project.createSourceFile(path, source, { overwrite: true });

  const cls = sf.getClasses().find((c) => c.getDecorator('Injectable'));
  if (!cls) {
    return { ok: false, ts: '', errors: ['no @Injectable class found'], todos: [], model: null };
  }

  const className = cls.getName() ?? 'AnonymousService';
  const decorator = cls.getDecorator('Injectable')!;
  const decArg = decorator.getArguments()[0];
  const providedIn = decArg ? readProvidedIn(decArg) : null;

  // --- Generated API clients are regenerated, never hand-migrated. ---
  if (isGeneratedService(source, path)) {
    const todo =
      `OpenAPI-generated API client \`${className}\` — regenerate from the spec for ` +
      `the React app (axios client), do not hand-migrate this file.`;
    const banner =
      `// MIGRATION_TODO(openapi): ${todo}\n` +
      `// The Angular source is left untouched below for reference.\n\n`;
    return {
      ok: true,
      ts: banner + source,
      errors: [],
      todos: [todo],
      model: { className, providedIn, generated: true, deps: [], lifecycle: [], todos: [todo] },
    };
  }

  const todos: string[] = [];
  const deps: ServiceDep[] = [];

  // --- Remove the @Injectable decorator. ---
  decorator.remove();

  // --- Drop Angular lifecycle interfaces from `implements`. ---
  for (const impl of cls.getImplements()) {
    const name = impl.getExpression().getText();
    if (LIFECYCLE_INTERFACES.has(name)) cls.removeImplements(impl);
  }

  // --- Convert `inject(X)` fields into constructor parameters (manual DI). ---
  interface InjectField {
    name: string;
    token: string;
    scope: Scope | undefined;
    isReadonly: boolean;
  }
  const injectFields: InjectField[] = [];
  for (const prop of [...cls.getProperties()]) {
    const init = prop.getInitializer();
    const m = init?.getText().match(/^inject\s*<[^>]*>\s*\(\s*([^)]*?)\s*\)|^inject\s*\(\s*([^)]*?)\s*\)/);
    if (!m) continue;
    const token = (m[1] ?? m[2] ?? '').trim();
    // Preserve an *explicit* access modifier only; an implicit-public field
    // must not gain a `public` keyword as a constructor parameter property.
    const mods = prop.getModifiers().map((mod) => mod.getText());
    const scope = mods.includes('private')
      ? Scope.Private
      : mods.includes('protected')
        ? Scope.Protected
        : mods.includes('public')
          ? Scope.Public
          : undefined;
    injectFields.push({
      name: prop.getName(),
      token,
      scope,
      isReadonly: mods.includes('readonly'),
    });
    deps.push({ propName: prop.getName(), token, via: 'inject' });
    prop.remove();
  }

  // --- Existing constructor-DI params also become explicit deps (flagged). ---
  const existingCtor = cls.getConstructors()[0];
  if (existingCtor) {
    for (const param of existingCtor.getParameters()) {
      const t = param.getTypeNode()?.getText();
      if (t) deps.push({ propName: param.getName(), token: t, via: 'constructor' });
      // Strip Angular DI param decorators (@Inject/@Optional/@Self/...).
      for (const d of param.getDecorators()) {
        if (ANGULAR_CORE_DROP.has(d.getName())) d.remove();
      }
    }
  }

  if (injectFields.length > 0) {
    if (existingCtor) {
      existingCtor.insertParameters(
        0,
        injectFields.map((f) => ({
          name: f.name,
          type: f.token,
          scope: f.scope,
          isReadonly: f.isReadonly,
        })),
      );
    } else {
      // Place the constructor right after the last field for readable output.
      const members = cls.getMembers();
      let idx = 0;
      members.forEach((mem, i) => {
        if (Node.isPropertyDeclaration(mem)) idx = i + 1;
      });
      cls.insertConstructor(idx, {
        parameters: injectFields.map((f) => ({
          name: f.name,
          type: f.token,
          scope: f.scope,
          isReadonly: f.isReadonly,
        })),
      });
    }
    const list = injectFields.map((f) => `${f.name}: ${f.token}`).join(', ');
    const note = `DI: ${injectFields.length} inject() dependency(ies) -> constructor params (${list}); wire at construction or via a provider/context`;
    todos.push(note);
    const ctor = cls.getConstructors()[0];
    ctor?.addStatements(`// MIGRATION_TODO(di): ${note}`);
  } else if (existingCtor) {
    const note = `DI: constructor-injected dependencies -> wire at construction or via a provider/context`;
    todos.push(note);
    existingCtor.insertStatements(0, `// MIGRATION_TODO(di): ${note}`);
  }

  // --- Flag lifecycle hooks: kept, but no longer auto-invoked in React. ---
  const lifecycle: string[] = [];
  for (const method of cls.getMethods()) {
    const name = method.getName();
    if (!LIFECYCLE_HOOKS.has(name)) continue;
    lifecycle.push(name);
    const kind = name === 'ngOnDestroy' ? 'call on teardown / context cleanup' : 'call explicitly during init';
    const note = `lifecycle \`${name}\` — Angular no longer auto-invokes this; ${kind}`;
    todos.push(note);
    method.insertStatements(0, `// MIGRATION_TODO(lifecycle): ${note}`);
  }

  // --- Prune Angular DI/lifecycle imports from `@angular/core`. ---
  for (const imp of sf.getImportDeclarations()) {
    if (imp.getModuleSpecifierValue() !== '@angular/core') continue;
    for (const named of imp.getNamedImports()) {
      if (ANGULAR_CORE_DROP.has(named.getName())) named.remove();
    }
    if (imp.getNamedImports().length === 0 && !imp.getDefaultImport() && !imp.getNamespaceImport()) {
      imp.remove();
    }
  }

  const model: ServiceModel = { className, providedIn, generated: false, deps, lifecycle, todos };

  let ts: string;
  try {
    ts = await prettier.format(sf.getFullText(), {
      parser: 'babel-ts',
      singleQuote: true,
      printWidth: 100,
    });
  } catch (e) {
    return {
      ok: false,
      ts: sf.getFullText(),
      errors: [`prettier failed: ${(e as Error).message}`],
      todos,
      model,
    };
  }

  return { ok: true, ts, errors: [], todos, model };
}

/** Read `providedIn: 'root'` (etc.) out of the `@Injectable({...})` argument. */
function readProvidedIn(arg: Node): string | null {
  const oe = arg.asKind(SyntaxKind.ObjectLiteralExpression);
  if (!oe) return null;
  const prop = oe.getProperty('providedIn');
  if (!prop || !Node.isPropertyAssignment(prop)) return null;
  const init = prop.getInitializer();
  return init && Node.isStringLiteral(init) ? init.getLiteralValue() : null;
}
