import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { transformService } from '../src/transform-service.js';

const here = dirname(fileURLToPath(import.meta.url));
const APP = resolve(here, '../../../references/onecx-shell-ui/src/app');

function load(rel: string): { src: string; path: string } {
  const path = resolve(APP, rel);
  return { src: readFileSync(path, 'utf8'), path };
}

describe('service (@Injectable) -> plain TS module', () => {
  it('hand-written service: decorator stripped, inject() -> ctor params, stays a class', async () => {
    const { src, path } = load('shell/services/parameters.service.ts');
    const r = await transformService(src, path);
    expect(r.ok).toBe(true);
    expect(r.model!.generated).toBe(false);
    // @Injectable and its interface are gone; the class remains a class.
    expect(r.ts).not.toMatch(/@Injectable/);
    expect(r.ts).toContain('export class ParametersService {');
    expect(r.ts).not.toMatch(/implements\s+OnDestroy/);
    // The three inject() deps become explicit constructor parameters.
    expect(r.model!.deps.map((d) => d.propName)).toEqual([
      'appStateService',
      'remoteComponentsService',
      'parameterBffService',
    ]);
    expect(r.ts).toMatch(/constructor\(\s*private readonly appStateService: AppStateService/);
    expect(r.ts).not.toMatch(/=\s*inject\(/);
    // `this.` references survive untouched (a service is not restructured).
    expect(r.ts).toContain('this.init()');
    // The Angular-only core import is dropped entirely.
    expect(r.ts).not.toMatch(/from '@angular\/core'/);
  });

  it('lifecycle hooks are kept but flagged (React no longer auto-invokes them)', async () => {
    const { src, path } = load('shell/services/parameters.service.ts');
    const r = await transformService(src, path);
    expect(r.model!.lifecycle).toEqual(['ngOnDestroy']);
    expect(r.ts).toMatch(/MIGRATION_TODO\(lifecycle\): lifecycle `ngOnDestroy`/);
    // Body preserved.
    expect(r.ts).toContain('this.parametersTopic.destroy()');
  });

  it('DI is surfaced as residue, never silently resolved', async () => {
    const { src, path } = load('shell/services/parameters.service.ts');
    const r = await transformService(src, path);
    expect(r.todos.some((t) => /MIGRATION_TODO/.test(t) || /DI:/.test(t))).toBe(true);
    expect(r.ts).toMatch(/MIGRATION_TODO\(di\)/);
  });

  it('generated OpenAPI client is flagged for regeneration, not hand-migrated', async () => {
    const { src, path } = load('shared/generated/api/permission.service.ts');
    const r = await transformService(src, path);
    expect(r.ok).toBe(true);
    expect(r.model!.generated).toBe(true);
    expect(r.ts).toMatch(/MIGRATION_TODO\(openapi\)/);
    // The original source is preserved verbatim below the banner (untouched).
    expect(r.ts).toContain('auto generated by OpenAPI Generator');
    expect(r.ts).toMatch(/@Injectable/); // not stripped — this file is not migrated
  });

  it('a .ts with no @Injectable class is reported as not-a-service', async () => {
    const r = await transformService('export const x = 1;', 'plain.ts');
    expect(r.ok).toBe(false);
    expect(r.model).toBeNull();
    expect(r.errors).toEqual(['no @Injectable class found']);
  });

  it('is deterministic (same input -> identical output)', async () => {
    const { src, path } = load('shell/services/parameters.service.ts');
    const a = await transformService(src, path);
    const b = await transformService(src, path);
    expect(a.ts).toBe(b.ts);
  });

  it('golden: parameters.service.ts', async () => {
    const { src, path } = load('shell/services/parameters.service.ts');
    const r = await transformService(src, path);
    expect(r.ts).toMatchSnapshot();
  });
});
